############################
## Code folding
############################

# Set to true to disable code folding
disable_codefolding = false
# Set to "hide" or "show" all codes by default
codefolding_show = "show"
# Set to true to exclude the "Show/hide all" button
codefolding_nobutton = false